export const FETCH_LEVEL1 = 'FETCH_LEVEL1';
export const ON_DATE_CHANGE = 'ON_DATE_CHANGE';
export const ON_TIME_CHANGE = 'ON_TIME_CHANGE';
export const ON_FILE_DROP = 'ON_FILE_DROP';

export const FETCH_LEVEL2 = 'FETCH_LEVEL2';
export const ON_FROM_DATE = 'ON_FROM_DATE';
export const ON_TO_DATE = 'ON_TO_DATE';
export const ON_CHECKBOX_CHANGE = 'ON_CHECKBOX_CHANGE';
export const ON_DISABLE_CHECK = 'ON_DISABLE_CHECK';

export const ON_MENU_CHANGE = 'ON_MENU_CHANGE';
export const ON_OPEN_WEEK = 'ON_OPEN_WEEK';
export const ON_SELECT_WEEK_CHANGE = 'ON_SELECT_WEEK_CHANGE';

export const FETCH_LEVEL4 = 'FETCH_LEVEL4';
export const FETCH_LEVEL4_ONE = 'FETCH_LEVEL4_ONE';

export const ON_STARRATE_CLICK = 'ON_STARRATE_CLICK';
export const FETCH_COMICS = 'FETCH_COMICS';
export const FETCH_COMIC = 'FETCH_COMIC';